
= NewRelic Connector Release Notes
////
[<System_Name>: NewRelic]
////
:keywords: NewRelic


The NewRelic connector facilitates connections between Mule integration and NewRelic applications. The NewRelic connector  provides to know the applicationlist,application metrics,server list,server metrics associated to a particular account etc.

*Guide:* <Connector_Guide_Link>
////
Points to the docs.mulesoft pages for documentation on the functional aspects of the connector. e.g.: link:/mule-user-guide/v/3.7/microsoft-sharepoint-2013-connector[Microsoft SharePoint 2013 Connector]
////

== Version 1.0 - 1 January 2016
////
<Connector_Version> : Describes the connector version, such as “V2013”, “V4.0”, “V4.0.1-HF2” or whatever used for release]
<Release_date> : The date on which the connector is released (not when the notes are written, mind you)
////
=== Contents

- Compatibility
- Features
- Fixed in this Release
- Known Issues
- Support Resources

=== Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime |3.7.0
|NewRelic |1.0
|===





=== Features

. Version 1.0 Supported Operations
The NewRelic Connector 1.0 allows you to perform the following operations:

NewRelic Connector Operations +

1. Get Applications +
2. Get Users List +
3. Get Metric Names +
4. Get Application Instances +
5. Get servers +
6. Get Hosts List +
7. Get Browser Applications +
8. Update Server Name by ApplicationId +
9. Get User Details by userid +

=== Fixed in this Release
Version 1.0 Fixed in this Release
There are no bug fixes in this release.


=== Known Issues

Version 1.0 Known Issues
There are no reported issues that are unresolved in this release.

=== Support Resources

- Learn how to link:/mule-user-guide/v/3.7/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
- Access MuleSoft’s MuleForge link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
- To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].

